#ifndef __KEYBOARD_H__
#define __KEYBOARD_H__

#include "types.h"

struct age_key {
  b8 down;
  b8 up;
  b8 click;
};

enum age_keys {
  AGE_ESCAPE = 0,
  AGE_ENTER,
  AGE_TAB,
  AGE_BACKSPACE,
  AGE_INSERT,
  AGE_DELETE,
  AGE_RIGHT,
  AGE_LEFT,
  AGE_UP,
  AGE_DOWN,
  AGE_PAGE_UP,
  AGE_PAGE_DOWN,
  AGE_HOME,
  AGE_END,
  AGE_CAPS_LOCK,
  AGE_SCROLL_LOCK,
  AGE_NUM_LOCK,
  AGE_PRINT_SCREEN,
  AGE_PAUSE,
  AGE_F1,
  AGE_F2,
  AGE_F3,
  AGE_F4,
  AGE_F5,
  AGE_F6,
  AGE_F7,
  AGE_F8,
  AGE_F9,
  AGE_F10,
  AGE_F11,
  AGE_F12,
  AGE_PAD_DECIMAL = 33,
  AGE_PAD_DIVIDE,
  AGE_PAD_MULTIPLY,
  AGE_PAD_SUBTRACT,
  AGE_PAD_ADD,
  AGE_PAD_ENTER,
  AGE_PAD_EQUAL = 40,
  AGE_LEFT_SHIFT,
  AGE_LEFT_CONTROL,
  AGE_LEFT_ALT,
  AGE_LEFT_SUPER = 58,
  AGE_RIGHT_SHIFT = 60,
  AGE_RIGHT_CONTROL = 62,
  AGE_RIGHT_ALT,
  AGE_RIGHT_SUPER,
  AGE_WORLD_1 = 94,
  AGE_WORLD_2,
  AGE_PAD_0 = 97,
  AGE_PAD_1,
  AGE_PAD_2,
  AGE_PAD_3,
  AGE_PAD_4,
  AGE_PAD_5,
  AGE_PAD_6,
  AGE_PAD_7,
  AGE_PAD_8,
  AGE_PAD_9,
  AGE_KEY_COUNT,
  AGE_KEY_INVALID
};

struct age_key age_keyboard_get(enum age_keys key);

#endif/*__KEYBOARD_H__*/
